# Generated by Django 5.2 on 2025-04-09 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accountopening', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_budget', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_payments', models.PositiveIntegerField()),
                ('amount', models.BigIntegerField()),
                ('payment', models.BigIntegerField()),
                ('loan_type', models.IntegerField(choices=[(1, 'maskan'), (2, 'ezdevaj'), (3, 'daneshjou'), (4, 'kar')])),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BankAccount_loan', to='accountopening.bankaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_user', to='accountopening.user')),
            ],
        ),
    ]
